"""Move the auth-service identity database into the identity schema.

Revision ID: 20260916_0011
Revises: 20260915_0010

Source of truth for these 26 tables is the SQLite file
``/home/ubuntu/auth-service/users.db`` (owned by ``huangque-auth.service``,
``ExecStart=/usr/bin/python3 auth_server.py``; a second writer process
``huangque-invite-reward-claims`` runs ``process_invite_reward_claims.py``
every minute). This migration only creates the PostgreSQL tables; the backfill
and the read/write cutover are separate steps (see
``scripts/migrate_auth_identity.py``, ``docs/runbooks/postgresql-auth-identity-m6i.md``
and the M6 switch ``HQ_IDENTITY_STORE``).

Column parity with the SQLite source is deliberate — the same rules as M3A/M3D:

* ``TEXT`` stays ``TEXT``; ``INTEGER`` stays ``BIGINT`` (never ``INT``: an
  autoincrement id in an old install can exceed 32 bits); ``REAL`` would become
  ``DOUBLE PRECISION`` (this file currently has no REAL column); ``BLOB`` would
  become ``BYTEA`` (this file currently has none — the media go to COS, only
  object keys are stored).
* ``INTEGER`` columns that are really 0/1 flags become ``boolean``
  (``users.must_change``, ``users.card_initial_password``,
  ``invite_campaigns.code_required``,
  ``business_cards.{phone_public,email_public,address_public,wechat_qr_public,discoverable_in_network}``,
  ``announcement_campaigns.wechat_push_requested``). Every writer must
  normalise with ``bool()``: psycopg3 raises ``DatatypeMismatch`` when handed a
  0/1 int for a boolean column.
* Nullability is copied from the source, including its holes: columns declared
  without ``NOT NULL`` stay nullable here even when the current data happens to
  have no NULLs (``users.points``, ``users.must_change``, ``tokens.expires_at``,
  ``cli_device_grants.*`` …). Tightening a constraint the source never had
  would turn a bad-but-tolerated source row into a failed cutover.
* Time convention (verified against ``.schema`` plus sampled data on
  2026-09-16): **mixed, exactly as sourced.**
  ``users.created_at`` and ``tokens.created_at`` are TEXT
  ``YYYY-MM-DD HH:MM:SS`` in UTC (SQLite ``datetime('now')``), and stay TEXT;
  every other timestamp is a second-resolution Unix epoch and stays ``BIGINT``.
  No ``timestamptz`` is introduced anywhere, so no implicit conversion can shift
  a row during the shadow comparison. The TEXT ones keep a matching
  ``DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')`` so the
  cutover can insert without supplying the column and still produce the same
  string format as SQLite did.
* Autoincrement: the 15 source tables declared ``INTEGER PRIMARY KEY
  AUTOINCREMENT`` become ``BIGINT GENERATED BY DEFAULT AS IDENTITY``. The
  backfill carries the source ids over verbatim and then pushes each sequence
  past ``max(id)`` **and** past the source ``sqlite_sequence.seq`` — SQLite's
  AUTOINCREMENT never reuses an id, while a fresh PostgreSQL sequence would
  reuse the ids of deleted rows.
* ``sqlite_sequence`` (SQLite's internal AUTOINCREMENT bookkeeping table) is
  **not** migrated; it has no business meaning and its value is consumed by the
  backfiller only to set the PostgreSQL sequences (see above).
* The source declares **no** ``FOREIGN KEY`` at all, and none is added here:
  rows are logically linked by ``users.id`` / ``username``, but turning those
  links into real constraints would make the cutover fail on the legacy rows
  the source happily tolerates (orphaned ``inviter_user_id``, deleted users).
  Tables are ordered below by logical dependency (``users`` and ``tokens``
  first) so the backfiller can run top-to-bottom.
* ``identity.users.points`` is a **balance snapshot column**, copied row-for-row
  and never recomputed here; the point movements themselves (``points_audit``,
  ``point_transfers``, ``recharge_orders``, ``virtual_pay_orders``,
  ``membership_recharge_records``, ``membership_upgrade_records``,
  ``invite_reward_point_records``) belong to the ledger domain (0012).
"""

from alembic import op
import sqlalchemy as sa

revision = "20260916_0011"
down_revision = "20260915_0010"
branch_labels = None
depends_on = None

# SQLite 的 TEXT 时间列口径：UTC 的 'YYYY-MM-DD HH:MM:SS'（datetime('now')）。
# 保持同一格式，避免切换后同一列里混进两种写法。
SQLITE_NOW_TEXT = "to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')"


def upgrade() -> None:
    # ------------------------------------------------------------------
    # 1. users -> identity.users
    #    账号主表：登录、点数余额快照、会员档位、账号状态。
    #    主写者进程是 auth_server.py（huangque-auth.service）；
    #    另有一个**跨域的兜底写者** leadgen_api.py（huangque-leadgen-api），
    #    它在 auth 点数接口不可用时直连本库 UPDATE points（见 Runbook 写者清单），
    #    切写必须把它一起纳入，否则出现「auth 写 PG、leadgen 写 SQLite」的双权威。
    # ------------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True,
                  comment="账号自增主键（源表 INTEGER PRIMARY KEY AUTOINCREMENT）；"
                          "邀请/名片/画布等表都按它做逻辑外键"),
        sa.Column("username", sa.Text(), nullable=False, unique=True,
                  comment="登录名：手机号或早期英文名；全局唯一，是登录与令牌归属的键"),
        sa.Column("pw_hash", sa.Text(), nullable=False,
                  comment="口令哈希（sha256 十六进制）。**敏感列**：任何日志、报表、报错都不得回显"),
        sa.Column("pw_salt", sa.Text(), nullable=False,
                  comment="口令盐值（随机十六进制）。**敏感列**：与 pw_hash 成对使用，禁止回显"),
        sa.Column("display_name", sa.Text(),
                  comment="展示名（默认与 username 相同，可由用户修改）"),
        sa.Column("points", sa.BigInteger(), server_default=sa.text("0"),
                  comment="点数余额快照（可空，源即如此；NULL 按 0 处理）。**只整行照搬、绝不重算**，"
                          "点数流水归 ledger 域 0012"),
        sa.Column("role", sa.Text(), server_default=sa.text("'member'"),
                  comment="角色：member=普通用户，admin=管理员（后台接口的鉴权依据）"),
        sa.Column("must_change", sa.Boolean(), server_default=sa.text("true"),
                  comment="是否强制改密（源为 0/1 整数，此处为真布尔；写入方必须 bool() 归一化）"),
        sa.Column("created_at", sa.Text(), server_default=sa.text(SQLITE_NOW_TEXT),
                  comment="注册时间，TEXT 口径 UTC 'YYYY-MM-DD HH:MM:SS'（与 SQLite 源逐字节一致，"
                          "绝不做时区换算）"),
        sa.Column("account_id", sa.Text(),
                  comment="对外账号编号，形如 HQ53J2AQ；唯一（NULL 可重复，源为唯一索引）"),
        sa.Column("wx_openid", sa.Text(),
                  comment="微信小程序 openid；唯一（NULL 可重复）。**个人信息**，报表与日志避免回显"),
        sa.Column("account_status", sa.Text(), nullable=False, server_default=sa.text("'active'"),
                  comment="账号状态：active=正常，banned=封禁（封禁后登录与令牌校验一律拒绝）"),
        sa.Column("membership_tier", sa.Text(), nullable=False, server_default=sa.text("''"),
                  comment="会员档位：''=无 / experience=体验官 / partner=合伙人 / initiator=发起人"),
        sa.Column("membership_started_at", sa.BigInteger(),
                  comment="会员生效时间，秒级 Unix 时间戳；无会员为 NULL"),
        sa.Column("membership_expires_at", sa.BigInteger(),
                  comment="会员到期时间，秒级 Unix 时间戳；无会员为 NULL"),
        sa.Column("card_initial_password", sa.Boolean(), nullable=False,
                  server_default=sa.text("false"),
                  comment="名片初始口令标记（源为 0/1 整数，此处为真布尔）"),
        schema="identity",
    )
    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX idx_users_account_id ON identity.users(account_id)"
        )
    )
    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX idx_users_wx_openid ON identity.users(wx_openid) "
            "WHERE wx_openid IS NOT NULL"
        )
    )

    # ------------------------------------------------------------------
    # 2. tokens -> identity.tokens
    #    网页端登录令牌。写者只有 auth_server.py（登录签发、登出/改密删除、
    #    过期清理）；被登出的用户令牌立即失效。
    # ------------------------------------------------------------------
    op.create_table(
        "tokens",
        sa.Column("token", sa.Text(), primary_key=True,
                  comment="登录令牌原文（同时是主键）。**敏感列**：禁止回显、禁止进日志"),
        sa.Column("username", sa.Text(), nullable=False,
                  comment="令牌归属账号；与 identity.users.username 逻辑对应（非物理外键）"),
        sa.Column("created_at", sa.Text(), server_default=sa.text(SQLITE_NOW_TEXT),
                  comment="签发时间，TEXT 口径 UTC 'YYYY-MM-DD HH:MM:SS'（与 SQLite 源一致）"),
        sa.Column("expires_at", sa.BigInteger(),
                  comment="过期时间，秒级 Unix 时间戳；NULL=永不过期（历史遗留的长期令牌）"),
        sa.Column("scope", sa.Text(), nullable=False, server_default=sa.text("'account'"),
                  comment="令牌用途：account=网页登录；CLI 令牌走 identity.cli_refresh_tokens，不在此表"),
        schema="identity",
    )

    # ------------------------------------------------------------------
    # 3. cli_device_grants -> identity.cli_device_grants
    #    CLI 设备授权码流程（RFC 8628 风格）：start → approve → poll → 换 token。
    #    写者 auth_server.py（内部调用 hq_cli_api 的函数，传入自己的连接工厂）；
    #    登出/封禁会由 auth_server 或 invites 把 revoked_at 置位。
    # ------------------------------------------------------------------
    op.create_table(
        "cli_device_grants",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True,
                  comment="授权记录自增主键（源表 INTEGER PRIMARY KEY AUTOINCREMENT）"),
        sa.Column("device_code_hash", sa.Text(), nullable=False, unique=True,
                  comment="设备码的哈希（不存原文）。**敏感列**：只参与比对，禁止回显"),
        sa.Column("user_code_hash", sa.Text(), nullable=False, unique=True,
                  comment="用户码的哈希（不存原文）。**敏感列**：只参与比对，禁止回显"),
        sa.Column("client_name", sa.Text(), nullable=False,
                  comment="发起授权的客户端名（如 HQ CLI live smoke），供管理员核对"),
        sa.Column("requested_scopes_json", sa.Text(), nullable=False,
                  comment="客户端申请的权限范围，JSON 数组文本（如 [\"profile:read\",\"ip12:write\"]）"),
        sa.Column("approved_scopes_json", sa.Text(),
                  comment="管理员实际批准的权限范围，JSON 数组文本；未批准为 NULL"),
        sa.Column("username", sa.Text(),
                  comment="批准后归属的账号；待批准（pending）时为 NULL"),
        sa.Column("status", sa.Text(), nullable=False,
                  comment="状态机：pending=待批准 / approved=已批准 / issued=已换发令牌 / expired=过期"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="发起时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        sa.Column("expires_at", sa.BigInteger(), nullable=False,
                  comment="本次授权的过期时间，秒级 Unix 时间戳；过期后 status 置 expired"),
        sa.Column("approved_at", sa.BigInteger(),
                  comment="管理员批准时间，秒级 Unix 时间戳；未批准为 NULL"),
        sa.Column("last_poll_at", sa.BigInteger(), nullable=False, server_default=sa.text("0"),
                  comment="最近一次轮询时间，秒级 Unix 时间戳；从未轮询为 0"),
        sa.Column("token_hash", sa.Text(), unique=True,
                  comment="换发出的 CLI 访问令牌哈希（不存原文）。**敏感列**；未换发为 NULL"),
        sa.Column("token_expires_at", sa.BigInteger(),
                  comment="CLI 访问令牌过期时间，秒级 Unix 时间戳；未换发为 NULL"),
        sa.Column("revoked_at", sa.BigInteger(),
                  comment="撤销时间，秒级 Unix 时间戳；NULL=未撤销（登出、封禁、令牌轮换会置位）"),
        schema="identity",
    )
    op.create_index(
        "idx_cli_grants_user", "cli_device_grants",
        ["username", "token_expires_at"], schema="identity",
    )

    # ------------------------------------------------------------------
    # 4. cli_refresh_tokens -> identity.cli_refresh_tokens
    #    CLI 刷新令牌：一次有效（used_at 置位后不得复用），依赖
    #    identity.cli_device_grants.id 做逻辑外键。写者 auth_server.py。
    # ------------------------------------------------------------------
    op.create_table(
        "cli_refresh_tokens",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True,
                  comment="自增主键（源表 INTEGER PRIMARY KEY AUTOINCREMENT）"),
        sa.Column("grant_id", sa.BigInteger(), nullable=False,
                  comment="所属设备授权记录，对应 identity.cli_device_grants.id（逻辑外键）"),
        sa.Column("token_hash", sa.Text(), nullable=False, unique=True,
                  comment="刷新令牌哈希（不存原文）。**敏感列**：只参与比对与轮换，禁止回显"),
        sa.Column("expires_at", sa.BigInteger(), nullable=False,
                  comment="过期时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        sa.Column("used_at", sa.BigInteger(),
                  comment="被使用时间，秒级 Unix 时间戳；NULL=未使用。非空即表示该刷新令牌已作废"),
        schema="identity",
    )
    op.create_index(
        "idx_cli_refresh_grant", "cli_refresh_tokens",
        ["grant_id", "used_at", "expires_at"], schema="identity",
    )

    # ------------------------------------------------------------------
    # 5. cli_action_requests -> identity.cli_action_requests
    #    CLI 写操作的幂等账本（按 username+action+request_id 去重，7 天 TTL 清理）。
    #    注意：**当前代码已无读写方**——旧的 hq_cli_api.py 建过并写过它，
    #    现行版本不再引用（最后一次写入 2026-09-01）。建表 + 回填只为保留历史，
    #    切写时可以先不接；若确认长期无人使用，归档期再评估是否清理。
    # ------------------------------------------------------------------
    op.create_table(
        "cli_action_requests",
        sa.Column("username", sa.Text(), primary_key=True,
                  comment="发起操作的账号（复合主键第 1 列）"),
        sa.Column("action", sa.Text(), primary_key=True,
                  comment="操作类型键，如 ip12-message / ip12-publish（复合主键第 2 列）"),
        sa.Column("request_id", sa.Text(), primary_key=True,
                  comment="客户端生成的请求编号（复合主键第 3 列，幂等键的核心部分）"),
        sa.Column("project_id", sa.Text(), nullable=False,
                  comment="操作所属项目编号；同一请求在不同项目下互不影响"),
        sa.Column("request_hash", sa.Text(), nullable=False,
                  comment="请求体指纹：同一 request_id 换内容即视为冲突。**敏感列**（含请求摘要），只比对不回显"),
        sa.Column("status", sa.Text(), nullable=False,
                  comment="执行状态：completed / failed / uncertain（超时未确认，客户端可安全重放）"),
        sa.Column("http_status", sa.BigInteger(),
                  comment="上游返回的 HTTP 状态码；uncertain 时为 NULL"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="受理时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        sa.Column("updated_at", sa.BigInteger(), nullable=False,
                  comment="最后状态变更时间，秒级 Unix 时间戳；回填冲突护栏按此列比对"),
        schema="identity",
    )
    op.create_index(
        "idx_cli_action_active", "cli_action_requests",
        ["username", "action", "project_id", "status", "updated_at"], schema="identity",
    )

    # ------------------------------------------------------------------
    # 6. membership_audit -> identity.membership_audit
    #    会员档位变更审计，只增不改：后台改档、上线名单迁移都追加一行。
    # ------------------------------------------------------------------
    op.create_table(
        "membership_audit",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True,
                  comment="自增主键（源表 INTEGER PRIMARY KEY AUTOINCREMENT）；读取方按 id DESC 排序"),
        sa.Column("username", sa.Text(), nullable=False,
                  comment="被改档的账号"),
        sa.Column("before_tier", sa.Text(), nullable=False, server_default=sa.text("''"),
                  comment="变更前档位；''=无会员"),
        sa.Column("after_tier", sa.Text(), nullable=False, server_default=sa.text("''"),
                  comment="变更后档位；''=取消会员"),
        sa.Column("before_expires_at", sa.BigInteger(),
                  comment="变更前到期时间，秒级 Unix 时间戳；原无会员为 NULL"),
        sa.Column("after_expires_at", sa.BigInteger(),
                  comment="变更后到期时间，秒级 Unix 时间戳；取消会员为 NULL"),
        sa.Column("operator", sa.Text(), nullable=False,
                  comment="操作人：管理员用户名，或 launch-migration 之类的自动化标识"),
        sa.Column("reason", sa.Text(),
                  comment="变更原因（中文自由文本，如「会员上线显式名单迁移」）"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="发生时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        schema="identity",
    )
    op.execute(
        sa.text(
            "CREATE INDEX idx_membership_audit_user "
            "ON identity.membership_audit(username, id DESC)"
        )
    )

    # ------------------------------------------------------------------
    # 7. membership_voice_slot_entitlements -> identity.membership_voice_slot_entitlements
    #    声音克隆槽位权益：一个账号一行，记录权益来源与来源订单。
    #    内测免费化后槽位不再收费，但权益行仍需保留（决定用户能开几个声音）。
    # ------------------------------------------------------------------
    op.create_table(
        "membership_voice_slot_entitlements",
        sa.Column("username", sa.Text(), primary_key=True,
                  comment="账号；一个账号只有一行权益"),
        sa.Column("source", sa.Text(), nullable=False,
                  comment="权益来源：launch_backfill=上线名单回填 / order=购买 / admin=人工开通"),
        sa.Column("source_order_id", sa.Text(),
                  comment="来源订单编号（如 launch-backfill:user:372）；人工开通或回填可能为空"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="开通时间，秒级 Unix 时间戳（与 SQLite 源口径一致）；退款按 username+source_order_id 撤销"),
        schema="identity",
    )

    # ------------------------------------------------------------------
    # 8. friendships -> identity.friendships
    #    好友关系（双向各一行）。写者 auth_server.py（接受好友申请时成对插入）。
    # ------------------------------------------------------------------
    op.create_table(
        "friendships",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True,
                  comment="自增主键（源表 INTEGER PRIMARY KEY AUTOINCREMENT）"),
        sa.Column("username", sa.Text(), nullable=False,
                  comment="关系拥有者（好友列表按它查询）"),
        sa.Column("friend_username", sa.Text(), nullable=False,
                  comment="好友账号；与 username 组成唯一对（双向存储，插两行）"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="成为好友的时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        sa.UniqueConstraint("username", "friend_username",
                           name="uq_friendships_pair"),
        schema="identity",
    )
    op.execute(
        sa.text(
            "CREATE INDEX idx_friendships_user "
            "ON identity.friendships(username, id DESC)"
        )
    )

    # ------------------------------------------------------------------
    # 9. friend_requests -> identity.friend_requests
    #    好友申请：pending → accepted/rejected/withdrawn。
    #    删除好友时旧申请行的 status 会被改写成 'removed:<id>'（源即如此，
    #    非枚举值，读方按前缀判断），迁移不得做值归一化。
    # ------------------------------------------------------------------
    op.create_table(
        "friend_requests",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True,
                  comment="自增主键（源表 INTEGER PRIMARY KEY AUTOINCREMENT）"),
        sa.Column("from_username", sa.Text(), nullable=False,
                  comment="申请人账号"),
        sa.Column("to_username", sa.Text(), nullable=False,
                  comment="被申请人账号"),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'pending'"),
                  comment="状态：pending/accepted/rejected/withdrawn，"
                          "以及历史遗留的 removed:<原行id>（前缀语义，原样保留）"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="申请时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        sa.Column("reviewed_at", sa.BigInteger(),
                  comment="处理时间，秒级 Unix 时间戳；未处理为 NULL"),
        sa.UniqueConstraint("from_username", "to_username", "status",
                            name="uq_friend_requests_triple"),
        schema="identity",
    )
    op.execute(
        sa.text(
            "CREATE INDEX idx_friend_requests_from "
            "ON identity.friend_requests(from_username, status, id DESC)"
        )
    )
    op.execute(
        sa.text(
            "CREATE INDEX idx_friend_requests_to "
            "ON identity.friend_requests(to_username, status, id DESC)"
        )
    )

    # ------------------------------------------------------------------
    # 10. invite_campaigns -> identity.invite_campaigns
    #     邀请活动配置（生产只有 1 行「长期邀请活动」）。写者 invites.py（后台）。
    # ------------------------------------------------------------------
    op.create_table(
        "invite_campaigns",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True,
                  comment="活动自增主键（源表 INTEGER PRIMARY KEY AUTOINCREMENT）；"
                          "所有邀请关系都按它归属"),
        sa.Column("name", sa.Text(), nullable=False,
                  comment="活动名（如「长期邀请活动」，后台展示用）"),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'enabled'"),
                  comment="活动状态：enabled=进行中 / disabled=停用（停用后不再签发邀请码）"),
        sa.Column("start_at", sa.BigInteger(),
                  comment="开始时间，秒级 Unix 时间戳；NULL=立即开始"),
        sa.Column("end_at", sa.BigInteger(),
                  comment="结束时间，秒级 Unix 时间戳；NULL=长期有效"),
        sa.Column("code_required", sa.Boolean(), nullable=False, server_default=sa.text("false"),
                  comment="是否必须邀请码才能注册（源为 0/1 整数，此处为真布尔）"),
        sa.Column("daily_invite_limit", sa.BigInteger(), nullable=False,
                  server_default=sa.text("50"),
                  comment="每个邀请人每日可签发的邀请码上限（生产已调到 500）"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="创建时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        sa.Column("updated_at", sa.BigInteger(), nullable=False,
                  comment="最后修改时间，秒级 Unix 时间戳；回填冲突护栏按此列比对"),
        schema="identity",
    )

    # ------------------------------------------------------------------
    # 11. invite_codes -> identity.invite_codes
    #     邀请码：一个邀请人在一个活动下的可用码唯一（部分唯一索引）。
    # ------------------------------------------------------------------
    op.create_table(
        "invite_codes",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True,
                  comment="自增主键（源表 INTEGER PRIMARY KEY AUTOINCREMENT）"),
        sa.Column("campaign_id", sa.BigInteger(), nullable=False,
                  comment="所属活动，对应 identity.invite_campaigns.id（逻辑外键）"),
        sa.Column("inviter_user_id", sa.BigInteger(), nullable=False,
                  comment="签发人，对应 identity.users.id（逻辑外键）"),
        sa.Column("code", sa.Text(), nullable=False, unique=True,
                  comment="邀请码明文（6 位大写字母数字，去掉易混字符）；注册时按它绑定邀请关系"),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'active'"),
                  comment="状态：active=可用 / used=已被使用 / revoked=已作废；"
                          "只有 active 参与唯一约束"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="签发时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        schema="identity",
    )
    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX idx_invite_codes_active_user "
            "ON identity.invite_codes(campaign_id, inviter_user_id) WHERE status='active'"
        )
    )
    op.create_index(
        "idx_invite_codes_lookup", "invite_codes", ["code", "status"], schema="identity",
    )

    # ------------------------------------------------------------------
    # 12. user_invites -> identity.user_invites
    #     邀请关系（一个被邀请人只能绑定一次）。写者 invites.py；
    #     读方还有 auth_server（注册流程）与 business_cards（名片引流归因）。
    # ------------------------------------------------------------------
    op.create_table(
        "user_invites",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True,
                  comment="自增主键（源表 INTEGER PRIMARY KEY AUTOINCREMENT）"),
        sa.Column("campaign_id", sa.BigInteger(), nullable=False,
                  comment="所属活动，对应 identity.invite_campaigns.id（逻辑外键）"),
        sa.Column("inviter_user_id", sa.BigInteger(), nullable=False,
                  comment="邀请人，对应 identity.users.id（逻辑外键）"),
        sa.Column("invitee_user_id", sa.BigInteger(), nullable=False, unique=True,
                  comment="被邀请人，对应 identity.users.id；一人只能被邀请一次（唯一）"),
        sa.Column("invite_code", sa.Text(), nullable=False,
                  comment="绑定用的邀请码（保留明文，便于后台核对来源）"),
        sa.Column("source", sa.Text(), nullable=False,
                  comment="来源：web_link / web_manual / miniprogram / miniprogram_card / admin"),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'bound'"),
                  comment="关系状态：bound=已绑定 / invalid=风控判无效（见 invalid_reason）"),
        sa.Column("risk_status", sa.Text(), nullable=False, server_default=sa.text("'normal'"),
                  comment="风控标记：normal=正常 / review=待人工复核 / blocked=已拦截"),
        sa.Column("bound_at", sa.BigInteger(), nullable=False,
                  comment="绑定时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        sa.Column("ip_hash", sa.Text(),
                  comment="注册 IP 的哈希（不存原文，30 天保留）。**敏感列**：只比对不回显"),
        sa.Column("device_hash", sa.Text(),
                  comment="设备指纹哈希。**敏感列**：只比对不回显；与 ip_hash 一起用于刷号识别"),
        sa.Column("updated_at", sa.BigInteger(), nullable=False,
                  comment="最后修改时间，秒级 Unix 时间戳；回填冲突护栏按此列比对"),
        sa.Column("invalid_reason", sa.Text(),
                  comment="判无效原因（中文自由文本）；生产当前全为 NULL"),
        schema="identity",
    )
    op.create_index("idx_user_invites_bound_at", "user_invites", ["bound_at"], schema="identity")
    op.create_index(
        "idx_user_invites_campaign_status", "user_invites",
        ["campaign_id", "status"], schema="identity",
    )
    op.execute(
        sa.text(
            "CREATE INDEX idx_user_invites_device_time "
            "ON identity.user_invites(device_hash, bound_at DESC)"
        )
    )
    op.execute(
        sa.text(
            "CREATE INDEX idx_user_invites_inviter_time "
            "ON identity.user_invites(inviter_user_id, bound_at DESC)"
        )
    )
    op.execute(
        sa.text(
            "CREATE INDEX idx_user_invites_ip_time "
            "ON identity.user_invites(ip_hash, bound_at DESC)"
        )
    )

    # ------------------------------------------------------------------
    # 13. invite_reward_claims -> identity.invite_reward_claims
    #     邀请奖励领取凭据：被邀请人升级触发一行，7 天内可领取，过期作废。
    #     注意：本表带 reward_points（实际发放点数），是**奖励凭据**而非点数流水——
    #     归属按任务书留在 identity 域；真正的点数变动记在 ledger 域的
    #     points_audit / invite_reward_point_records，两边靠 id 对应。
    # ------------------------------------------------------------------
    op.create_table(
        "invite_reward_claims",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True,
                  comment="自增主键（源表 INTEGER PRIMARY KEY AUTOINCREMENT）"),
        sa.Column("upgrade_record_id", sa.BigInteger(), nullable=False, unique=True,
                  comment="触发本次奖励的升级记录编号（ledger 域 membership_upgrade_records.id）；"
                          "唯一，保证同一次升级只生成一份奖励"),
        sa.Column("source_order_id", sa.Text(),
                  comment="触发升级的订单编号（如 HQ26080321464137D330AFD7）；退款撤销时按它溯源"),
        sa.Column("invite_relation_id", sa.BigInteger(), nullable=False,
                  comment="邀请关系编号，对应 identity.user_invites.id（逻辑外键）"),
        sa.Column("direct_inviter_user_id", sa.BigInteger(), nullable=False,
                  comment="直邀人，对应 identity.users.id；过期清算与列表查询按它过滤"),
        sa.Column("invitee_user_id", sa.BigInteger(), nullable=False,
                  comment="被邀请人（升级方），对应 identity.users.id"),
        sa.Column("target_level", sa.Text(), nullable=False,
                  comment="达标档位：experience / partner / initiator（决定奖励金额与发放对象）"),
        sa.Column("event_type", sa.Text(), nullable=False, server_default=sa.text("'upgrade'"),
                  comment="事件类型：upgrade=升级达标（现行唯一取值，预留其它事件）"),
        sa.Column("status", sa.Text(), nullable=False,
                  comment="状态：pending=待领取 / credited=已发放 / expired=已过期 / voided=已作废"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="生成时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        sa.Column("expires_at", sa.BigInteger(), nullable=False,
                  comment="领取截止时间，秒级 Unix 时间戳（生成后 7 天）；过期由每分钟的清算服务置 expired"),
        sa.Column("recipient_user_id", sa.BigInteger(),
                  comment="实际收款人，对应 identity.users.id（多层转赠时可能不是直邀人）；未发放为 NULL"),
        sa.Column("recipient_level_snapshot", sa.Text(),
                  comment="发放瞬间收款人的档位快照（比例按快照算，事后改档不影响已发奖励）"),
        sa.Column("reward_points", sa.BigInteger(), nullable=False, server_default=sa.text("0"),
                  comment="本次奖励点数（凭据金额，不是余额）；**不重算**，与 ledger 侧流水对应"),
        sa.Column("transfer_depth", sa.BigInteger(), nullable=False, server_default=sa.text("0"),
                  comment="转赠层数：0=直接发给自己（现行数据全为 0）"),
        sa.Column("settled_at", sa.BigInteger(),
                  comment="发放时间，秒级 Unix 时间戳；未发放为 NULL"),
        sa.Column("voided_at", sa.BigInteger(),
                  comment="作废时间，秒级 Unix 时间戳（升级订单退款时作废）；未作废为 NULL"),
        sa.Column("reason", sa.Text(),
                  comment="状态说明，如 membership_qualified / order_refunded"),
        sa.Column("updated_at", sa.BigInteger(), nullable=False,
                  comment="最后修改时间，秒级 Unix 时间戳；回填冲突护栏按此列比对"),
        schema="identity",
    )
    op.create_index(
        "idx_invite_claims_expiry", "invite_reward_claims",
        ["status", "expires_at"], schema="identity",
    )
    op.create_index(
        "idx_invite_claims_owner_status", "invite_reward_claims",
        ["direct_inviter_user_id", "status", "expires_at"], schema="identity",
    )

    # ------------------------------------------------------------------
    # 14. invite_reward_notifications -> identity.invite_reward_notifications
    #     邀请奖励的站内提示：按 operation_key 幂等（同一动作只提示一次）。
    #     生产当前为空表。
    # ------------------------------------------------------------------
    op.create_table(
        "invite_reward_notifications",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True,
                  comment="自增主键（源表 INTEGER PRIMARY KEY AUTOINCREMENT）"),
        sa.Column("user_id", sa.BigInteger(), nullable=False,
                  comment="提示接收人，对应 identity.users.id（逻辑外键）"),
        sa.Column("claim_id", sa.BigInteger(),
                  comment="关联的奖励凭据，对应 identity.invite_reward_claims.id；非奖励提示为 NULL"),
        sa.Column("notice_type", sa.Text(), nullable=False,
                  comment="提示类型键（决定前端文案与跳转）"),
        sa.Column("operation_key", sa.Text(), nullable=False, unique=True,
                  comment="幂等键：同一业务动作重复触发只会有一行提示"),
        sa.Column("payload_json", sa.Text(), nullable=False, server_default=sa.text("'{}'"),
                  comment="提示内容 JSON 文本（标题、正文、关联编号）"),
        sa.Column("last_shown_day", sa.Text(),
                  comment="最近展示日期（YYYY-MM-DD，上海时区），用于一天只弹一次"),
        sa.Column("read_at", sa.BigInteger(),
                  comment="已读时间，秒级 Unix 时间戳；未读为 NULL"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="创建时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        sa.Column("updated_at", sa.BigInteger(), nullable=False,
                  comment="最后修改时间，秒级 Unix 时间戳；回填冲突护栏按此列比对"),
        schema="identity",
    )
    op.execute(
        sa.text(
            "CREATE INDEX idx_invite_reward_notices_user "
            "ON identity.invite_reward_notifications(user_id, notice_type, read_at, id)"
        )
    )

    # ------------------------------------------------------------------
    # 15. invite_admin_audit -> identity.invite_admin_audit
    #     邀请后台的操作审计（配置变更、关系改判），只增不改。
    #     源表没有索引，读取总是全表倒序，故不建索引；
    #     invite_relation_id=0 表示这次动作不是针对某条邀请关系（如配置变更）。
    # ------------------------------------------------------------------
    op.create_table(
        "invite_admin_audit",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True,
                  comment="自增主键（源表 INTEGER PRIMARY KEY AUTOINCREMENT）"),
        sa.Column("operator_user_id", sa.BigInteger(), nullable=False,
                  comment="操作管理员，对应 identity.users.id（逻辑外键）"),
        sa.Column("invite_relation_id", sa.BigInteger(), nullable=False,
                  comment="被操作的邀请关系编号；0=与具体关系无关（如配置变更）"),
        sa.Column("action", sa.Text(), nullable=False,
                  comment="动作键，如 config_update / relation_invalidate"),
        sa.Column("reason", sa.Text(),
                  comment="操作原因（中文自由文本，可能为空串）"),
        sa.Column("before_json", sa.Text(),
                  comment="动作前快照 JSON 文本；配置类动作才有，其它为 NULL"),
        sa.Column("after_json", sa.Text(),
                  comment="动作后快照 JSON 文本；配置类动作才有，其它为 NULL"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="发生时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        schema="identity",
    )

    # ------------------------------------------------------------------
    # 16. canvas_boards -> identity.canvas_boards
    #     协作画布：data_json 是全量画布快照。写者 auth_server.py（画布接口）。
    # ------------------------------------------------------------------
    op.create_table(
        "canvas_boards",
        sa.Column("id", sa.Text(), primary_key=True,
                  comment="画布编号，形如 cb_7fViA3JF9h4d8VG0（服务端生成，字符串主键）"),
        sa.Column("owner_username", sa.Text(), nullable=False,
                  comment="画布拥有者账号；成员权限记录在 identity.canvas_members"),
        sa.Column("name", sa.Text(), nullable=False,
                  comment="画布名（用户可改，默认「未命名协作画布」）"),
        sa.Column("data_json", sa.Text(), nullable=False,
                  comment="画布全量快照 JSON 文本（节点、连线、视口）；含用户素材路径，不要外泄"),
        sa.Column("version", sa.BigInteger(), nullable=False, server_default=sa.text("1"),
                  comment="快照版本号；每次保存自增，与 identity.canvas_ops 的增量操作对账"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="创建时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        sa.Column("updated_at", sa.BigInteger(), nullable=False,
                  comment="最后保存时间，秒级 Unix 时间戳；列表按它倒序，回填冲突护栏按此列比对"),
        schema="identity",
    )
    op.execute(
        sa.text(
            "CREATE INDEX idx_canvas_boards_owner "
            "ON identity.canvas_boards(owner_username, updated_at DESC)"
        )
    )

    # ------------------------------------------------------------------
    # 17. canvas_members -> identity.canvas_members
    #     画布协作成员与角色（viewer/editor）。
    # ------------------------------------------------------------------
    op.create_table(
        "canvas_members",
        sa.Column("board_id", sa.Text(), primary_key=True,
                  comment="画布编号，对应 identity.canvas_boards.id（复合主键第 1 列）"),
        sa.Column("username", sa.Text(), primary_key=True,
                  comment="成员账号（复合主键第 2 列）"),
        sa.Column("role", sa.Text(), nullable=False, server_default=sa.text("'viewer'"),
                  comment="成员角色：viewer=只读 / editor=可编辑"),
        sa.Column("invited_by", sa.Text(), nullable=False,
                  comment="邀请人账号（画布拥有者）"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="加入时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        schema="identity",
    )
    op.create_index(
        "idx_canvas_members_user", "canvas_members", ["username", "board_id"], schema="identity",
    )

    # ------------------------------------------------------------------
    # 18. canvas_ops -> identity.canvas_ops
    #     画布增量操作日志：按 (board_id, version) 单调推进，op_id 保证重放幂等。
    #     实时同步时客户端按 version 拉取缺失操作。
    # ------------------------------------------------------------------
    op.create_table(
        "canvas_ops",
        sa.Column("board_id", sa.Text(), primary_key=True,
                  comment="画布编号（复合主键第 1 列）"),
        sa.Column("version", sa.BigInteger(), primary_key=True,
                  comment="操作序号，从 1 单调递增（复合主键第 2 列）；缺号即可判断丢操作"),
        sa.Column("op_id", sa.Text(), nullable=False,
                  comment="操作唯一编号（客户端 id + 序列），同一操作重传不会写两行"),
        sa.Column("client_id", sa.Text(), nullable=False,
                  comment="提交操作的客户端标识，用于冲突判定与在线状态"),
        sa.Column("username", sa.Text(), nullable=False,
                  comment="提交人账号"),
        sa.Column("ops_json", sa.Text(), nullable=False,
                  comment="操作内容 JSON 数组文本（node.create/move/delete 等），重放即得画布状态"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="提交时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        sa.UniqueConstraint("board_id", "op_id", name="uq_canvas_ops_op"),
        schema="identity",
    )
    op.create_index(
        "idx_canvas_ops_board_version", "canvas_ops", ["board_id", "version"], schema="identity",
    )

    # ------------------------------------------------------------------
    # 19. canvas_presence -> identity.canvas_presence
    #     画布在线状态心跳：一个客户端一行，超过 TTL 视为离线。
    # ------------------------------------------------------------------
    op.create_table(
        "canvas_presence",
        sa.Column("board_id", sa.Text(), primary_key=True,
                  comment="画布编号（复合主键第 1 列）"),
        sa.Column("client_id", sa.Text(), primary_key=True,
                  comment="客户端标识（复合主键第 2 列）；同一用户多标签页算多个在线"),
        sa.Column("username", sa.Text(), nullable=False,
                  comment="在线用户账号（前端显示「谁在画布上」）"),
        sa.Column("last_seen", sa.BigInteger(), nullable=False,
                  comment="最近心跳时间，秒级 Unix 时间戳；早于 TTL 即视为离线，可安全清理"),
        schema="identity",
    )
    op.create_index(
        "idx_canvas_presence_board_seen", "canvas_presence",
        ["board_id", "last_seen"], schema="identity",
    )

    # ------------------------------------------------------------------
    # 20. business_cards -> identity.business_cards
    #     个人名片：与 users 一对一（user_id 即主键）。写者 business_cards.py
    #     （由 auth_server 调用）；读方还有 invite_network（名片网络关系）。
    # ------------------------------------------------------------------
    op.create_table(
        "business_cards",
        sa.Column("user_id", sa.BigInteger(), primary_key=True,
                  comment="名片归属账号，直接复用 identity.users.id（一对一，非自增）"),
        sa.Column("public_id", sa.Text(), nullable=False, unique=True,
                  comment="对外公开编号（名片链接按它访问，避免暴露 user_id）"),
        sa.Column("name", sa.Text(), nullable=False, server_default=sa.text("''"),
                  comment="姓名/称呼（名片主标题）"),
        sa.Column("headline", sa.Text(), nullable=False, server_default=sa.text("''"),
                  comment="一句话头衔（如「主理人」）"),
        sa.Column("company", sa.Text(), nullable=False, server_default=sa.text("''"),
                  comment="公司/机构名"),
        sa.Column("bio", sa.Text(), nullable=False, server_default=sa.text("''"),
                  comment="自我介绍正文"),
        sa.Column("phone", sa.Text(), nullable=False, server_default=sa.text("''"),
                  comment="手机号。**个人信息**：是否对外由 phone_public 决定，报表与日志避免回显"),
        sa.Column("email", sa.Text(), nullable=False, server_default=sa.text("''"),
                  comment="邮箱。**个人信息**：是否对外由 email_public 决定"),
        sa.Column("address", sa.Text(), nullable=False, server_default=sa.text("''"),
                  comment="地址。**个人信息**：是否对外由 address_public 决定"),
        sa.Column("tags_json", sa.Text(), nullable=False, server_default=sa.text("'[]'"),
                  comment="标签，JSON 数组文本；历史行里出现过空串 ''（源即如此，原样保留）"),
        sa.Column("works_json", sa.Text(), nullable=False, server_default=sa.text("'[]'"),
                  comment="作品列表，JSON 数组文本（标题 + 媒体键）"),
        sa.Column("links_json", sa.Text(), nullable=False, server_default=sa.text("'[]'"),
                  comment="外部链接，JSON 数组文本；历史行里出现过空串 ''"),
        sa.Column("avatar_key", sa.Text(), nullable=False, server_default=sa.text("''"),
                  comment="头像在 COS 的对象键（cards/avatar/…），不是完整 URL"),
        sa.Column("wechat_qr_key", sa.Text(), nullable=False, server_default=sa.text("''"),
                  comment="微信二维码在 COS 的对象键；是否对外由 wechat_qr_public 决定"),
        sa.Column("phone_public", sa.Boolean(), nullable=False, server_default=sa.text("false"),
                  comment="手机号是否对外公开（源为 0/1 整数，此处为真布尔）"),
        sa.Column("email_public", sa.Boolean(), nullable=False, server_default=sa.text("false"),
                  comment="邮箱是否对外公开（源为 0/1 整数，此处为真布尔）"),
        sa.Column("address_public", sa.Boolean(), nullable=False, server_default=sa.text("false"),
                  comment="地址是否对外公开（源为 0/1 整数，此处为真布尔）"),
        sa.Column("wechat_qr_public", sa.Boolean(), nullable=False, server_default=sa.text("false"),
                  comment="微信二维码是否对外公开（源为 0/1 整数，此处为真布尔）"),
        sa.Column("discoverable_in_network", sa.Boolean(), nullable=False,
                  server_default=sa.text("true"),
                  comment="是否在名片网络里可被检索（默认 true；关闭后不出现在网络列表）"),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'draft'"),
                  comment="状态：draft=草稿（只有本人可见）/ published=已发布"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="创建时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        sa.Column("updated_at", sa.BigInteger(), nullable=False,
                  comment="最后修改时间，秒级 Unix 时间戳；回填冲突护栏按此列比对"),
        sa.Column("published_at", sa.BigInteger(),
                  comment="首次发布时间，秒级 Unix 时间戳；从未发布为 NULL"),
        sa.Column("miniprogram_openid", sa.Text(),
                  comment="小程序 openid，用于「我的名片」免登录识别；唯一（NULL 可重复）。**个人信息**"),
        schema="identity",
    )
    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX idx_cards_miniprogram_openid "
            "ON identity.business_cards(miniprogram_openid) "
            "WHERE miniprogram_openid IS NOT NULL"
        )
    )
    op.create_index(
        "idx_cards_network", "business_cards",
        ["user_id", "status", "discoverable_in_network"], schema="identity",
    )
    op.create_index(
        "idx_cards_public", "business_cards", ["public_id", "status"], schema="identity",
    )

    # ------------------------------------------------------------------
    # 21. card_referral_journeys -> identity.card_referral_journeys
    #     名片引流旅程：从匿名访问 → 注册 → 发布名片，一条链路一行。
    #     匿名旅程保留 30 天、已转化 365 天（由业务代码清理）。
    # ------------------------------------------------------------------
    op.create_table(
        "card_referral_journeys",
        sa.Column("journey_id", sa.Text(), primary_key=True,
                  comment="旅程编号（服务端生成的字符串主键）"),
        sa.Column("campaign_id", sa.BigInteger(), nullable=False,
                  comment="所属活动，对应 identity.invite_campaigns.id（逻辑外键）"),
        sa.Column("card_public_id", sa.Text(), nullable=False,
                  comment="被访问的名片，对应 identity.business_cards.public_id（逻辑外键）"),
        sa.Column("inviter_user_id", sa.BigInteger(), nullable=False,
                  comment="名片主人（邀请人），对应 identity.users.id（逻辑外键）"),
        sa.Column("source", sa.Text(), nullable=False,
                  comment="引流来源：miniprogram_card / web_card 等"),
        sa.Column("visited_at", sa.BigInteger(), nullable=False,
                  comment="首次访问时间，秒级 Unix 时间戳；匿名旅程清理与统计的基准列"),
        sa.Column("card_started_at", sa.BigInteger(),
                  comment="访客开始填写名片的时间，秒级 Unix 时间戳；未开始为 NULL"),
        sa.Column("registered_user_id", sa.BigInteger(),
                  comment="转化后的注册账号，对应 identity.users.id；未转化为 NULL（唯一）"),
        sa.Column("invite_relation_id", sa.BigInteger(),
                  comment="转化生成的邀请关系，对应 identity.user_invites.id；未转化为 NULL"),
        sa.Column("registered_at", sa.BigInteger(),
                  comment="注册时间，秒级 Unix 时间戳；未转化为 NULL"),
        sa.Column("published_at", sa.BigInteger(),
                  comment="访客发布自己名片的时间，秒级 Unix 时间戳；未发布为 NULL"),
        sa.Column("expires_at", sa.BigInteger(), nullable=False,
                  comment="旅程可回查截止时间，秒级 Unix 时间戳（按是否转化取 30/365 天）"),
        schema="identity",
    )
    op.execute(
        sa.text(
            "CREATE INDEX idx_card_referral_anonymous_time "
            "ON identity.card_referral_journeys(visited_at) WHERE registered_user_id IS NULL"
        )
    )
    op.create_index(
        "idx_card_referral_expiry", "card_referral_journeys", ["expires_at"], schema="identity",
    )
    op.execute(
        sa.text(
            "CREATE INDEX idx_card_referral_inviter_time "
            "ON identity.card_referral_journeys(inviter_user_id, visited_at DESC)"
        )
    )
    op.execute(
        sa.text(
            "CREATE INDEX idx_card_referral_registered_time "
            "ON identity.card_referral_journeys(registered_at) WHERE registered_user_id IS NOT NULL"
        )
    )
    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX idx_card_referral_registered_user "
            "ON identity.card_referral_journeys(registered_user_id) "
            "WHERE registered_user_id IS NOT NULL"
        )
    )

    # ------------------------------------------------------------------
    # 22. network_node_ids -> identity.network_node_ids
    #     名片网络里的全局节点编号（一个账号一个，供关系图渲染与分享）。
    # ------------------------------------------------------------------
    op.create_table(
        "network_node_ids",
        sa.Column("user_id", sa.BigInteger(), primary_key=True,
                  comment="账号，直接复用 identity.users.id（一对一，非自增）"),
        sa.Column("node_id", sa.Text(), nullable=False, unique=True,
                  comment="对外节点编号，形如 N-T_Nv6mBvNKKv0A4fsX-Mj3"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="分配时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        schema="identity",
    )

    # ------------------------------------------------------------------
    # 23. user_notifications -> identity.user_notifications
    #     站内通知（公告投递 + 系统提示）。campaign_id 非空表示来自某次公告，
    #     同一公告对同一账号只能有一行（部分唯一索引）。
    # ------------------------------------------------------------------
    op.create_table(
        "user_notifications",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True,
                  comment="自增主键（源表 INTEGER PRIMARY KEY AUTOINCREMENT）"),
        sa.Column("username", sa.Text(), nullable=False,
                  comment="接收人账号"),
        sa.Column("kind", sa.Text(), nullable=False, server_default=sa.text("'system'"),
                  comment="通知类型：system=系统提示 / announcement=全站公告"),
        sa.Column("title", sa.Text(), nullable=False,
                  comment="通知标题"),
        sa.Column("detail", sa.Text(), nullable=False,
                  comment="通知正文（公告正文可能很长）"),
        sa.Column("created_by", sa.Text(), nullable=False,
                  comment="创建人（管理员用户名，或自动化标识）"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="创建时间，秒级 Unix 时间戳；列表按 id 倒序，回填冲突护栏按此列比对"),
        sa.Column("campaign_id", sa.BigInteger(),
                  comment="来源公告，对应 identity.announcement_campaigns.id；非公告通知为 NULL"),
        sa.Column("read_at", sa.BigInteger(),
                  comment="已读时间，秒级 Unix 时间戳；未读为 NULL（角标按未读数统计）"),
        sa.Column("popup_snoozed_until", sa.BigInteger(),
                  comment="弹窗再提醒时间，秒级 Unix 时间戳；用户「稍后再说」后设置；未设为 NULL"),
        schema="identity",
    )
    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX idx_user_notifications_campaign_user "
            "ON identity.user_notifications(campaign_id, username) WHERE campaign_id IS NOT NULL"
        )
    )
    op.execute(
        sa.text(
            "CREATE INDEX idx_user_notifications_user "
            "ON identity.user_notifications(username, id DESC)"
        )
    )

    # ------------------------------------------------------------------
    # 24. announcement_campaigns -> identity.announcement_campaigns
    #     全站公告活动：发布时按 audience_json 选人，向 user_notifications 批量投递。
    # ------------------------------------------------------------------
    op.create_table(
        "announcement_campaigns",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True,
                  comment="自增主键（源表 INTEGER PRIMARY KEY AUTOINCREMENT）"),
        sa.Column("title", sa.Text(), nullable=False,
                  comment="公告标题"),
        sa.Column("detail", sa.Text(), nullable=False,
                  comment="公告正文（多行文本）"),
        sa.Column("audience_json", sa.Text(), nullable=False,
                  comment="收件人筛选条件 JSON 文本，如 {\"mode\":\"all\"} 或按档位筛选"),
        sa.Column("status", sa.Text(), nullable=False, server_default=sa.text("'published'"),
                  comment="状态：published=已发布 / recalled=已撤回（撤回后前端不再展示）"),
        sa.Column("recipient_count", sa.BigInteger(), nullable=False, server_default=sa.text("0"),
                  comment="实际投递人数（发布时冻结，与告警/复核口径一致）"),
        sa.Column("breakdown_json", sa.Text(), nullable=False, server_default=sa.text("'{}'"),
                  comment="投递人数按会员档位拆分，JSON 文本（如 {\"experience\":133,\"none\":37}）"),
        sa.Column("created_by", sa.Text(), nullable=False,
                  comment="发布人（管理员用户名）"),
        sa.Column("request_id", sa.Text(), nullable=False, unique=True,
                  comment="发布幂等键（后台每次发布生成一个），防重复群发"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="创建时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        sa.Column("published_at", sa.BigInteger(), nullable=False,
                  comment="发布时间，秒级 Unix 时间戳"),
        sa.Column("recalled_at", sa.BigInteger(),
                  comment="撤回时间，秒级 Unix 时间戳；未撤回为 NULL"),
        sa.Column("recalled_by", sa.Text(),
                  comment="撤回人（管理员用户名）；未撤回为 NULL"),
        sa.Column("wechat_push_requested", sa.Boolean(), nullable=False,
                  server_default=sa.text("false"),
                  comment="发布时是否同时请求微信订阅消息推送（源为 0/1 整数，此处为真布尔）"),
        sa.Column("wechat_recipient_count", sa.BigInteger(), nullable=False,
                  server_default=sa.text("0"),
                  comment="微信订阅消息实际入队人数；未请求推送为 0"),
        schema="identity",
    )
    op.execute(
        sa.text(
            "CREATE INDEX idx_announcement_campaigns_created "
            "ON identity.announcement_campaigns(id DESC)"
        )
    )

    # ------------------------------------------------------------------
    # 25. wechat_subscription_grants -> identity.wechat_subscription_grants
    #     微信订阅消息授权余量：用户每点一次「允许」累计一次推送机会。
    # ------------------------------------------------------------------
    op.create_table(
        "wechat_subscription_grants",
        sa.Column("username", sa.Text(), primary_key=True,
                  comment="账号（复合主键第 1 列）"),
        sa.Column("event_type", sa.Text(), primary_key=True,
                  comment="订阅事件类型，如 work_complete（复合主键第 2 列）"),
        sa.Column("template_id", sa.Text(), primary_key=True,
                  comment="微信模板编号（复合主键第 3 列）；换模板即换一行，历史余量各自保留"),
        sa.Column("openid", sa.Text(), nullable=False,
                  comment="接收推送的小程序 openid。**个人信息**：只比对不回显"),
        sa.Column("remaining", sa.BigInteger(), nullable=False, server_default=sa.text("0"),
                  comment="剩余可推送次数：用户每次授权 +1，成功推送 -1；为 0 时不得推送"),
        sa.Column("last_choice", sa.Text(), nullable=False, server_default=sa.text("''"),
                  comment="用户最近一次选择：accept=允许 / reject=拒绝；''=未选择过"),
        sa.Column("updated_at", sa.BigInteger(), nullable=False,
                  comment="最后变更时间，秒级 Unix 时间戳；回填冲突护栏按此列比对"),
        schema="identity",
    )

    # ------------------------------------------------------------------
    # 26. wechat_subscription_outbox -> identity.wechat_subscription_outbox
    #     微信订阅消息发件箱：业务只入队，worker 抢占投递（lease_until + 重试）。
    #     与 25 表的关系是「先扣余量、再入队」，靠 business_id 幂等。
    # ------------------------------------------------------------------
    op.create_table(
        "wechat_subscription_outbox",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), primary_key=True,
                  comment="自增主键（源表 INTEGER PRIMARY KEY AUTOINCREMENT）；"
                          "worker 按 (status,next_retry_at,id) 顺序抢件"),
        sa.Column("username", sa.Text(), nullable=False,
                  comment="接收人账号（复合唯一键第 1 列）"),
        sa.Column("event_type", sa.Text(), nullable=False,
                  comment="订阅事件类型（复合唯一键第 2 列），需与授权表匹配"),
        sa.Column("business_id", sa.Text(), nullable=False,
                  comment="业务幂等键，形如 job:5321（复合唯一键第 3 列）；同一业务只推一次"),
        sa.Column("job_id", sa.BigInteger(), nullable=False,
                  comment="关联的任务编号；非任务类消息为 0"),
        sa.Column("kind", sa.Text(), nullable=False,
                  comment="产物类型：sora_video / image / audio 等（决定模板字段与文案）"),
        sa.Column("template_id", sa.Text(), nullable=False,
                  comment="使用的微信模板编号（发布时的快照，换模板不影响已入队消息）"),
        sa.Column("status", sa.Text(), nullable=False,
                  comment="状态机：pending=待发 / sending=投递中 / sent=已发出 / failed=已放弃"),
        sa.Column("attempts", sa.BigInteger(), nullable=False, server_default=sa.text("0"),
                  comment="已尝试投递次数；超过上限置 failed，不再重试"),
        sa.Column("lease_until", sa.BigInteger(), nullable=False, server_default=sa.text("0"),
                  comment="投递租约到期时间，秒级 Unix 时间戳；0=无人占用（防止两个 worker 重复发）"),
        sa.Column("next_retry_at", sa.BigInteger(), nullable=False, server_default=sa.text("0"),
                  comment="下次可重试时间，秒级 Unix 时间戳；0=立即可发（当前数据全为 0）"),
        sa.Column("payload_json", sa.Text(), nullable=False,
                  comment="推送内容 JSON 文本（标题、时间、提示语）；发送前会按微信模板截断"),
        sa.Column("last_error", sa.Text(), nullable=False, server_default=sa.text("''"),
                  comment="最后一次失败原因（微信返回的错误摘要，已截断）"),
        sa.Column("created_at", sa.BigInteger(), nullable=False,
                  comment="入队时间，秒级 Unix 时间戳（与 SQLite 源口径一致）"),
        sa.Column("updated_at", sa.BigInteger(), nullable=False,
                  comment="最后状态变更时间，秒级 Unix 时间戳；回填冲突护栏按此列比对"),
        sa.Column("sent_at", sa.BigInteger(),
                  comment="发送成功时间，秒级 Unix 时间戳；未发出为 NULL"),
        sa.UniqueConstraint("username", "event_type", "business_id",
                            name="uq_wechat_sub_outbox_business"),
        schema="identity",
    )
    op.create_index(
        "idx_wechat_sub_ready", "wechat_subscription_outbox",
        ["status", "next_retry_at", "id"], schema="identity",
    )

    # ------------------------------------------------------------------
    # 表注释（AI 可读：每张表是什么、谁写谁读、权威何时切）
    # ------------------------------------------------------------------
    comments = {
        "users": "账号主表：登录、点数余额快照、会员档位与账号状态。"
                 "主写者是 auth_server.py（huangque-auth.service，/usr/bin/python3）；"
                 "leadgen_api.py 在 auth 点数接口失败时会兜底直连本表 UPDATE points，"
                 "切写必须同时覆盖这两个进程。points 只照搬余额，点数流水归 ledger 域。",
        "tokens": "网页登录令牌：登录签发、登出/改密删除、过期清理。"
                  "写读都在 auth_server.py；**令牌原文是凭证，禁止回显**。",
        "cli_device_grants": "CLI 设备授权码流程（start/approve/poll）。"
                             "auth_server.py 通过 hq_cli_api 的函数读写；只存各类码的哈希。",
        "cli_refresh_tokens": "CLI 刷新令牌，一次有效（used_at 置位即作废）；"
                              "grant_id 逻辑指向 cli_device_grants。auth_server.py 通过 hq_cli_api 读写。",
        "cli_action_requests": "CLI 写操作幂等账本（7 天 TTL）。"
                               "**当前代码已无读写方**：仅旧版 hq_cli_api.py 使用过，"
                               "最后写入 2026-09-01；迁移只为保留历史，不接线。",
        "membership_audit": "会员档位变更审计，只增不改：后台改档与上线名单迁移各追加一行。",
        "membership_voice_slot_entitlements": "声音克隆槽位权益（一账号一行）。"
                                              "内测免费化后槽位不收费，但权益行决定用户能开几个声音，必须保留。",
        "friendships": "好友关系，双向各存一行；接受好友申请时成对插入。",
        "friend_requests": "好友申请：pending → accepted/rejected/withdrawn；"
                           "删除好友会把 status 改写成 removed:<id>（前缀语义，勿做值归一化）。",
        "invite_campaigns": "邀请活动配置（生产仅 1 行「长期邀请活动」）；后台 invites.py 写入。",
        "invite_codes": "邀请码：一个邀请人在一个活动下的 active 码唯一；注册时按 code 绑定关系。",
        "user_invites": "邀请关系：一个被邀请人只能绑定一次；绑定时记录风控哈希（ip/device）。",
        "invite_reward_claims": "邀请奖励凭据：被邀请人升级触发一行，7 天内可领、过期作废。"
                                "本表带 reward_points 但它是**凭据**不是流水——"
                                "点数实际变动记在 ledger 域 points_audit / invite_reward_point_records。",
        "invite_reward_notifications": "邀请奖励站内提示：operation_key 幂等，同一动作只提示一次。生产当前为空表。",
        "invite_admin_audit": "邀请后台操作审计（配置变更、关系改判），只增不改；"
                              "invite_relation_id=0 表示与具体关系无关。",
        "canvas_boards": "协作画布：data_json 是全量快照，version 与 canvas_ops 的增量操作对账。",
        "canvas_members": "画布协作成员与角色（viewer/editor）。",
        "canvas_ops": "画布增量操作日志：(board_id, version) 单调推进，op_id 保证重放幂等。",
        "canvas_presence": "画布在线心跳：一客户端一行，超 TTL 视为离线，可安全清理。",
        "business_cards": "个人名片（与 users 一对一）：文本、作品、外链与四项公开开关。"
                          "写者 business_cards.py；读方还有 auth_server 与 invite_network。"
                          "phone/email/miniprogram_openid 是个人信息，报表与日志避免回显。",
        "card_referral_journeys": "名片引流旅程：匿名访问 → 注册 → 发布名片一条链路一行；"
                                  "匿名 30 天、已转化 365 天后由业务清理。",
        "network_node_ids": "名片网络的全局节点编号（一账号一个），供关系图与分享使用。",
        "user_notifications": "站内通知（公告投递 + 系统提示）：同一公告对同一账号只一行，读方按未读数显示角标。",
        "announcement_campaigns": "全站公告活动：发布时按 audience_json 选人批量投递，"
                                  "request_id 幂等防重复群发；撤回只改状态。",
        "wechat_subscription_grants": "微信订阅消息授权余量：用户点「允许」+1，发送成功 -1；余量 0 不得推送。",
        "wechat_subscription_outbox": "微信订阅消息发件箱：业务入队、worker 抢件投递；"
                                      "(username,event_type,business_id) 唯一保证同一业务只推一次。",
    }
    for table, text in comments.items():
        op.execute(
            sa.text(
                "COMMENT ON TABLE identity.%s IS '%s'"
                % (table, text.replace("'", "''"))
            )
        )


def downgrade() -> None:
    raise RuntimeError("Destructive PostgreSQL schema downgrade is not supported; restore a backup")
