'use strict';
const assert=require('node:assert/strict');
const canvas=require('../site/workbench/video-agent-canvas.js');
const session=require('../site/workbench/video-agent-session.js');
const routing=require('../site/workbench/video-agent-routing.js');

assert.deepEqual(canvas.clampPosition(-1,2),{x:0,y:1});
const card={x:.5,y:.5,width:300,height:240};
assert.equal(canvas.move(card,'ArrowLeft',false),true);
assert.equal(card.x,.49);
assert.equal(canvas.resize(card,'ArrowUp',true,{width:300,height:240}),true);
assert.equal(card.height,220);
assert.equal(session.isFresh(1000,1001),true);
assert.equal(session.isFresh(1001,1000),false);
assert.equal(session.isFresh(1,session.TTL_MS+2),false);
const routes=routing.ROUTES;
assert.deepEqual(Object.keys(routes).map(key=>routing.handoffTarget(routes[key])),['talking','create','open','motion','tryon','link']);
assert.equal(routing.effectiveRoute({function:'minimax'},true,false,routes.create),routes.create);
assert.equal(routing.cinematicMode(routes.story,true),'open');
const activations=[];
routing.activateRoute(routes.story,{onFunction:value=>activations.push(['function',value]),onCineMode:value=>activations.push(['mode',value])});
routing.activateRoute(routes.motion,{onFunction:value=>activations.push(['function',value]),onCineMode:value=>activations.push(['mode',value])});
assert.deepEqual(activations,[['function','cinematic'],['mode','open'],['function','cinematic'],['mode','motion']]);
const legacyDeepLink=[];routing.activateRoute({function:'cinematic'},{onFunction:value=>legacyDeepLink.push(['function',value]),onCineMode:value=>legacyDeepLink.push(['mode',value])});assert.deepEqual(legacyDeepLink,[['function','cinematic']]);
const historyRoundTrip=[];routing.activateRoute({function:'cinematic',cineMode:'motion'},{onFunction:value=>historyRoundTrip.push(['function',value]),onCineMode:value=>historyRoundTrip.push(['mode',value])});assert.deepEqual(historyRoundTrip,[['function','cinematic'],['mode','motion']]);

const source=require('node:fs').readFileSync(require('node:path').join(__dirname,'../site/workbench/video.html'),'utf8');
assert.match(source,/story:Object\.assign\(\{\},AGENT_ROUTE_SPECS\.story/);
assert.match(source,/var effectiveRoute=openVideoWorkbench\(route\)/);
assert.match(source,/historyReturnView==='workbench'\)openVideoWorkbench\(\{function:videoFunction,cineMode:videoFunction==='cinematic'\?cineMode:undefined/);
assert.match(source,/agentIdentity=agentSession\.createIdentityController/);
assert.doesNotMatch(source,/initializeAgentChatScroll\(\);\s*restoreAgentSession\(\);/);
assert.match(source,/id="agentPendingUpdateList"/);
(async()=>{
  const lifecycle=[];
  const identity=session.createIdentityController({cleanOwner:value=>String(value||'').trim().slice(0,64),deleteOwner:owner=>lifecycle.push(['delete',owner]),clearMemory:owner=>lifecycle.push(['clear',owner]),restore:owner=>lifecycle.push(['restore',owner])});
  assert.equal(identity.ensure(null),false);assert.equal(identity.isVerified(),false);assert.deepEqual(lifecycle,[]);
  assert.equal(identity.accept({username:'alice'}),true);assert.equal(identity.ensure({username:'alice'}),true);assert.deepEqual(lifecycle,[['clear','alice'],['restore','alice']]);
  assert.equal(identity.invalidate(),true);assert.equal(identity.isVerified(),false);assert.deepEqual(lifecycle.slice(-2),[['delete','alice'],['clear','']]);
  identity.accept({username:'bob'});assert.equal(identity.owner(),'bob');assert.deepEqual(lifecycle.slice(-2),[['clear','bob'],['restore','bob']]);
  const listeners=new Map(),host={addEventListener:(name,fn)=>listeners.set(name,fn),removeEventListener:(name,fn)=>{if(listeners.get(name)===fn)listeners.delete(name);}};
  const dragItem={x:.2,y:.2},classNames=new Set(),runtimeCard={offsetWidth:100,offsetHeight:80,style:{},classList:{add:name=>classNames.add(name),remove:name=>classNames.delete(name)},getBoundingClientRect:()=>({left:10,top:10})},stage={getBoundingClientRect:()=>({left:0,top:0,width:500,height:400})};
  assert.equal(canvas.bindPointerDrag({event:{button:0,clientX:20,clientY:20,preventDefault(){}},item:dragItem,card:runtimeCard,stage,host,scale:1,viewport:{x:0,y:0}}),true);listeners.get('pointermove')({clientX:250,clientY:200});assert.ok(dragItem.x>.2&&dragItem.y>.2);listeners.get('pointerup')();assert.equal(listeners.size,0);
  runtimeCard.offsetWidth=300;runtimeCard.offsetHeight=300;const resizeItem={width:300,height:300};assert.equal(canvas.bindPointerResize({event:{button:0,clientX:0,clientY:0,preventDefault(){},stopPropagation(){}},item:resizeItem,card:runtimeCard,host,scale:1}),true);listeners.get('pointermove')({clientX:50,clientY:50});assert.deepEqual(resizeItem,{width:350,height:350});listeners.get('pointerup')();
  let calls=0;
  const result=await session.reconcile(async(url,options)=>{calls++;assert.equal(url,'/api/gen/video/agent/actions/vpa_abc/reconcile');assert.equal(options.method,'POST');assert.equal(options.body,'{}');return {ok:true,json:async()=>({pending_action:{status:'submitted'}})};},'vpa_abc',{},()=>new Error('unexpected'));
  assert.equal(calls,1);assert.equal(result.pending_action.status,'submitted');
  await assert.rejects(session.reconcile(async()=>({ok:false,status:409,json:async()=>({code:'pending_reconcile_in_flight'})}),'vpa_abc',{},(response,data)=>Object.assign(new Error(data.code),{status:response.status,code:data.code})),error=>error.status===409&&error.code==='pending_reconcile_in_flight');
  console.log('video agent frontend runtime: ok');
})().catch(error=>{console.error(error);process.exitCode=1;});
